### PR TITLE
Multiline literals and enums should have trailing commas

### PR DESCRIPTION
**Pull request by cdzombak**
When writing a multiline literal or enumeration, leave a trailing comma on the last item. When entries are added or removed, this eliminates the need to touch unrelated lines. This in turn makes for cleaner diffs: only the truly relevant lines of code must be changed, and the resulting pull request is easier to review.

### CODE REVIEW

**Comment by mattbischoff** [comment]
> When writing a multiline literal or enumeration, leave a trailing comma on the last item. When entries are added or removed, this eliminates the need to touch unrelated lines. This in turn makes for cleaner diffs: only the truly relevant lines of code must be changed, and the resulting pull request is easier to review.

Totally agree that it leads to cleaner diffs, however I do think it’s at a loss to clarity. Specifically, in English, a comma separated list of items doesn’t end with a comma, so this reads unnaturally. Also, someone reading the code later may well think something is unintentionally missing and got removed due to a bad merge. This may seem like a small point, but I do think it warrants a little bit of a harder to read diff.

More generally, since this is not standard in Apple’s sample code, in current NYTimes codebases (to my knowledge), nor in the industry, it would be a large effort to move a lot of developers in this direction, and I’m just not sure it’s worth it. But I’m just some guy on the internet.

**Comment by paulbruneau** [comment]
I have never liked the practice myself, unless Chris and/or JC wish to come to my defense regarding method braces or `== NO` tests, in which case I love it.

**Comment by cdzombak** [comment]
> Specifically, in English, a comma separated list of items doesn’t end with a comma, so this reads unnaturally.

A lot of code doesn't follow English grammatical rules. And we don't write—or compare—English prose with the tools we use to manage our code.*

While I agree that readable, clear code is the ultimate goal goal, the artifacts we deal with in producing that code (diffs, for example) should also be clear; clearer diffs help us produce better code.

> Also, someone reading the code later may well think something is unintentionally missing and got removed due to a bad merge …

Not if we accept this style and begin making it commonplace.

And at least in the enum case, a bad merge is likely to result in compilation errors: you _will_ notice if an enumeration case goes missing.

> More generally, since this is not standard in Apple’s sample code…

Maybe not particularly common, but much of Apple's sample code is inconsistent enough I don't know that we can say this generally.

> …in current NYTimes codebases (to my knowledge)…

This is correct.

> …nor in the industry…

Again, I think "the industry" is widespread enough that it's hard to generalize. I have worked on large codebases where this style is common; that's how I picked up on it.

---

> Totally agree that it leads to cleaner diffs, however I do think it’s at a loss to clarity.

I agree with the first part of the sentence :trollface: but for the reasons above I don't think it is any less clear to readers of the code, and I think it can ultimately help result in a cleaner codebase.

---

* I fully realize we're having this discussion, about English prose, on GitHub. I argue that GitHub is _not_ the ideal tool for collaborating on English, though it works decently; and further that in fact we _do_ make concessions to git/GitHub/Markdown when we write and format English text in Markdown, in order to make commits, diffs, and rendering all easier.

**Comment by mattbischoff** [comment]
> I have never liked the practice myself, unless Chris and/or JC wish to come to my defense regarding method braces or == NO tests, in which case I love it.

Gotta love politics.

**Comment by andrewsardone** [comment]
:+1: @cdzombak

**Comment by loganmoseley** [comment]
The hanging comma leads to (a) a slightly more succinct diff; (b) one fewer misappropriated "blame" line—by not touching an existing enum line; and (c) a loss in conveying intent to a reader.

Reviewing a PRs happens once and the possible gain when reviewing a _commit1..commit2_ diff is marginal at best, so (a) does not have a lot of weight. When looking through the blame to see how and when an enum changed, (b) would be helpful, but this happens infrequently. Conveying intent to the **reader** of code is of utmost importance, so while (c) is minor, it will present itself much more often than a PR or diff/blame reviewing.

@cdzombak I have added this hanging comma many times myself. However, in order to support accepting this style into the guide, `a + b >> c`. It's not, so I can't.

**Comment by cdzombak** [comment]
> (b) one fewer misappropriated "blame" line—by not touching an existing enum line;
…
> (b) would be helpful, but this happens infrequently.

I hadn't even considered the implications for `git blame`! I use that heavily, mostly through Xcode's git integration, and it's immensely useful when exploring a codebase to be able to tell when and why a literal or enumeration changed.

Given that I _often_ leave blame view turned on when using Xcode, I argue this isn't exactly infrequent, or that at worst this [in]frequency from programmer to programmer.

> (c) a loss in conveying intent to a reader.

While the other arguments here (including my original ones!) are for the most part objective, this is just subjective, and I simply don't buy it; I don't find code written in this style less clear in intent than any other code.

**Comment by jmont** [comment]
I can't add anything that hasn't already been said, but just wanted to state my support for this PR.

Also, amen to @cdzombak :

> A lot of code doesn't follow English grammatical rules. And we don't write—or compare—English prose with the tools we use to manage our code.1
>
>While I agree that readable, clear code is the ultimate goal goal, the artifacts we deal with in producing that code (diffs, for example) should also be clear; clearer diffs help us produce better code.

**Comment by cdzombak** [comment]
As of https://github.com/cdzombak/objective-c-style-guide/commit/b34dae4bb1d69f47f4dd1b6aea88a3a164a73174 the proposed guideline now reads:

> When writing a multiline literal or enumeration, leave a trailing comma on the last item. When entries are added or removed, this eliminates the need to touch unrelated lines. This eliminates irrelevant git history from the unrelated lines of code, and it makes for cleaner diffs; only the truly relevant lines of code must be changed.

**Comment by cdzombak** [comment]
I'll add: I keep arguing for this because it's one of very few guidelines _which actually affect how well and quickly I can do my job_.

Having a cleaner history in git for each line allows me to be a more effective developer, particularly when exploring and changing an unfamiliar part of a large codebase; even metadata like "was this line changed the same day as this other line" is extremely useful, and Xcode's blame view does a good job surfacing this information. I don't see how this is so controversial, unless I somehow rely on git much more heavily than the average developer.

**Comment by mattbischoff** [comment]
> I don't see how this is so controversial, unless I somehow rely on git much more heavily than the average developer.

It’s a good point, but even as someone who relies on git very heavily, I don’t think this change has enough of a positive impact there to justify it. I’ve never had a problem figuring out `enum` intention in git history, but where I do often have that problem is in code that I’m reading in the present. I think that this change applied to the code I work on, I’d be often second-guessing what was going on with all the extra commas.

*Here are my final arguments against it*:

1. **The extra comma is not universally supported**. Consider the case of `NS_REQUIRES_NIL_TERMINATION ` which will throw a compiler error if you try the following:

```objectivec
[[UIAlertView alloc] initWithTitle:title message:message delegate:self cancelButtonTitle:cancelButtonTitle
                                      otherButtonTitles:@"1", @"2",  nil,];
``` 

This inconsistency is difficult to explain in the guide and will lead to even more cognitive costs when trying to follow the guide.

2. **The extra comma is non-standard in Objective-C codebases**. In a look through popular open source projects on GitHub, Apple sample code, and tutorials, I discovered very few that follow this convention. This is an added cost to teach every new engineer following the guide. I think we should try to limit there where possible as it’s already a lot to keep in your head.

3. **This is a _breaking_ change**. Many of the other additions to the style guide that have been made since its 1.0 release were additive, they didn’t throw existing code written with the guide out of compliance. I fear that this change will fracture the existing codebases in compliance, and without a public linter for the guide force people’s code into an essentially deprecated state if they follow the guide. Versioning might help solve this problem, but it’s not in place today.

4. **It’s ugly**. I’m generally a fan of arguments for productivity, objectivity, and speed, however the style guide serves many masters, and one of them is aesthetics. This looks gross to an English-speaker.

5. **There is no consensus.** Not to say that there always should be, but I think this points to the fact that there may be problems for enforcement.

**Comment by cdzombak** [comment]
> I’ve never had a problem figuring out `enum` intention in git history, 

My use case is often something like "was X added at the same time as Y?", which isn't really about intention, but this is a subjective point so I will move on.

> The extra comma is not universally supported.
…
> This inconsistency is difficult to explain in the guide and will lead to even more cognitive costs when trying to follow the guide.

Nothing is _universally_ supported in C/Objective-C. You could make the same argument against [the CGRect functions](https://github.com/NYTimes/objective-c-style-guide#cgrect-functions) section; accessor functions do not exist for every structure or even every CGGeometry structure, so why must we remember this special case? (Because though it's a special case, it's a special case which provides an objective advantage over the lowest common denominator.)

A subtle change in language can alleviate any difficulty in explanation. It's fairly clear already where this proposal says to use the trailing comma, but in any case we can adapt the rule to "literals and enums _when allowed_ or _possible_", similar in spirit to [this guideline from the GitHub Swift style guide](https://github.com/github/swift-style-guide#only-explicitly-refer-to-self-when-required).

> The extra comma is non-standard in Objective-C codebases. In a look through popular open source projects on GitHub, Apple sample code, and tutorials, I discovered very few that follow this convention. This is an added cost to teach every new engineer following the guide.

This is true of nearly anything in any style guide. In particular, I challenge you to find a particularly common ground between popular OSS projects, Apple sample code, and tutorials and this style guide's guidelines on [naming](https://github.com/NYTimes/objective-c-style-guide#naming)/[image naming](https://github.com/NYTimes/objective-c-style-guide#image-naming) or especially on [imports](https://github.com/NYTimes/objective-c-style-guide#imports).

The relatively small initial cost—a few-minute conversation, at worst—of introducing a new developer to this style does not outweigh the (concrete) advantages for _all_ developers, current and future, which I have outlined.

> This is a breaking change. Many of the other additions to the style guide that have been made since its 1.0 release were additive, they didn’t throw existing code written with the guide out of compliance.

This is true of nearly any addition to a style guide; indeed, if a rule didn't throw _some_ existing code out of compliance, what would be the advantage in adding it?

In this particular case, the language can be changed slightly to indicate that this style is preferred and developers should use this style in new or updated code. There is no harm in providing new and updated guidelines for an evolving codebase.

Did the NYT rewrite _all_ existing iOS code to comply with [its style guide](https://github.com/NYTimes/objective-c-style-guide) right away? The entire style guide is not a document which all existing code must comply with, it is instead a standard which new or changed code must comply with.

Further, this style guide did not before specify that this comma should be elided; therefore I disagree that this is truly a "breaking" change; it's more of a clarifying one.

A new rule in a style guide doesn't harm existing code, it provides guidelines for an evolving codebase.

> It’s ugly.
…
> This looks gross to an English-speaker.

The entirety of the C language looks gross to an English-speaker.

I disagree that "it's ugly", but this is a subjective point, so there's really no use in us arguing about it :heart: 

> There is no consensus. Not to say that there always should be, but I think this points to the fact that there may be problems for enforcement.

I'll refer you to "[tabs vs. spaces](https://github.com/NYTimes/objective-c-style-guide#spacing)" or "dot syntax vs square brackets](https://www.dzombak.com/blog/2015/03/Subjective-C--I-use-property--dot--syntax-liberally.html)".

The goal of a style guide is often to settle, within an organization, an issue where there is no broader consensus. In that spirit, "there is no consensus" is really more of an argument _in favor_ of adding this to the guide.

**Comment by loganmoseley** [comment]
I agree with every one of Matt's points; I agree with some of Chris's. The proposed change has not been proven necessary.

> I challenge you to find a particularly common ground between popular OSS projects...

Nope, the onus is on the one proposing the change. Not that you haven't tried, but this challenge is not allowed. Innocent until proven guilty.

> The goal of a style guide is often to settle, within an organization, an issue where there is no broader consensus. In that spirit, "there is no consensus" is really more of an argument in favor of adding this to the guide.

I'm not sure why you assert that "no consensus" logically leads to "mine is best." Maybe I'm reading this wrong.

**Comment by mattbischoff** [comment]
> This pull request contains merge conflicts that must be resolved.

Probably my fault due to that typo thing that was recently merged. Let me know if any questions arise in the merge.

File: README.md [hunk 1]
```diff
@@ -261,6 +261,38 @@ NSNumber *shouldUseLiterals = [NSNumber numberWithBool:YES];
 NSNumber *buildingZIPCode = [NSNumber numberWithInteger:10018];
 ```
 
+When writing a multiline literal or enumeration, leave a trailing comma on the last item. When entries are added or removed, this eliminates the need to touch unrelated lines. This eliminates irrelevant git history from the unrelated lines of code, and it makes for cleaner diffs; only the truly relevant lines of code must be changed.
```
Comment (mattbischoff) [inline README.md]: Existing `enums` and arrays in other parts of the guide should also be updated.

Comment (cdzombak) [inline README.md]: > Existing `enums` and arrays in other parts of the guide should also be updated.

Done in https://github.com/cdzombak/objective-c-style-guide/commit/4ebd3ce2733cb1f77a335c5bc680d47fabcee9ca .

**Comment by mattbischoff** [comment]
Still pretty skeptical that we should change this one.
